name: Run E2E tests

on:
  workflow_call:

jobs:
  e2e-tests:

    strategy:
        fail-fast: false
        matrix:
          browser: [chromium, firefox]
          shard: [1, 2, 3, 4]
          shards: [4]

    runs-on: ubuntu-latest

    # see https://playwright.dev/docs/ci#github-actions-via-containers
    container:
      image: mcr.microsoft.com/playwright:v1.29.0-focal

    steps:
      -
        uses: actions/checkout@v3
      -
        name: Playwright E2E Tests
        run: make e2e-tests-ci browser=${{ matrix.browser }} shard=${{ matrix.shard }} shards=${{ matrix.shards }}
      -
        name: Upload Playwright test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.browser }}-${{ matrix.shard }}
          path: test/e2e/test-results
          if-no-files-found: error
